### ISSUE TITLE
Question: What if I would like to access `pg` from the server object

### ISSUE THREAD

**Issue by doron2402** [jedireza/hapi-node-postgres#21]
Seems like you register pg to the `request` object: https://github.com/jedireza/hapi-node-postgres/blob/master/index.js#L32-L36

I'm using NSQ and added a plugin to listen to queue and I can only access the `server` object what would be the best way to access `pg`?

I thought about having a pr that expose the plugin using `server.expose` 

Also when I think about (just tested it) when using `onPreStart` `onPostStart` the plugin will failed since `reply.continue()` is undefined
Thanks,

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I thought about having a pr that expose the plugin using `server.expose`

We could do that right after we check for `config.native` support here: https://github.com/jedireza/hapi-node-postgres/blob/f1b90599a7ef654b17d48bfe84cb17c852fd4366/index.js#L22

> Also when I think about (just tested it) when using `onPreStart` `onPostStart` the plugin will failed since `reply.continue()` is undefined

Ideally, what we'd want to do is expose the `Pg.connect` function bound with the `config.connectionString` argument already. Then consumers using it could call that function passing only the callback/handler argument.

Since calling `Pg.connect` returns a `client` from the pool and a `done` callback to return it to the pool, a consumer will need to ensure the client is actually returned otherwise you could leak connections.

**Comment by doron2402** [comment]
Thanks for the quick and detailed response.

Would you mind if I'll open a Pr?

Thanks
